# Generated by Django 5.2.5 on 2025-08-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
